import { describe, expect, it } from "vitest";
import { createSealedFields } from "../src/index.js";

// Fixture generated by the Python reference implementation:
//
//   from cryptography.hazmat.primitives.ciphers.aead import AESGCM
//   key = bytes(range(32)); nonce = bytes(range(12))
//   ct = AESGCM(key).encrypt(nonce, plaintext.encode(), b"v1")
//   token = "v1:" + base64.urlsafe_b64encode(nonce + ct).decode()
//
// That is the exact scheme used by the production Python reference
// implementation (AES-256-GCM, nonce||ciphertext||tag, key version bound as
// AAD, urlsafe base64). Data sealed by either must unseal in the other.

const PY_KEY = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="; // bytes(range(32))
const PY_TOKEN =
  "v1:AAECAwQFBgcICQoLJHC5aLbIrnrjJuLq1oxYHua361GUWykdVBKApf_plJLlrQ4ZCnwmQ-wWBunh3zzykDCNKuLC";
const PY_PLAINTEXT = "cross-language sealed value — 你好";

describe("cross-language wire compatibility", () => {
  it("unseals a token produced by the Python reference implementation", () => {
    const sf = createSealedFields({ namespaces: { PII: { key: PY_KEY } } });
    expect(sf.unseal(PY_TOKEN)).toBe(PY_PLAINTEXT);
  });

  it("our tokens use the identical layout (nonce||ct||tag, AAD = version)", () => {
    const sf = createSealedFields({ namespaces: { PII: { key: PY_KEY } } });
    // Round-trip through our own implementation with the shared key proves
    // layout self-consistency; the fixture above proves Python agreement.
    const token = sf.seal(PY_PLAINTEXT);
    expect(sf.unseal(token)).toBe(PY_PLAINTEXT);
    expect(token).toMatch(/^v1:[A-Za-z0-9_-]+$/);
  });
});
